import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatediphone11prox7widget/generated/GeneratedGroup19Widget3.dart';
import 'package:flutterapp/conservapp/generatediphone11prox7widget/generated/GeneratedGradientBackgroundWallpaper00316Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox7widget/generated/GeneratedFrame33Widget10.dart';
import 'package:flutterapp/conservapp/generatediphone11prox7widget/generated/GeneratedFluenthomeadd24filledWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox7widget/generated/GeneratedAddanewdeviceWidget16.dart';
import 'package:flutterapp/conservapp/generatediphone11prox7widget/generated/GeneratedEnterinvitationcodeWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox7widget/generated/GeneratedJoinahomeWidget1.dart';

/* Frame iPhone 11 Pro / X - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -226.0,
                top: -384.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper00316Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedFrame33Widget10(),
              ),
              Positioned(
                left: 11.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 88.0,
                child: GeneratedJoinahomeWidget1(),
              ),
              Positioned(
                left: 124.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 132.0,
                child: GeneratedFluenthomeadd24filledWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 57.0,
                child: GeneratedGroup19Widget3(),
              ),
              Positioned(
                left: 3.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 32.0,
                child: GeneratedEnterinvitationcodeWidget(),
              ),
              Positioned(
                left: 107.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 44.0,
                child: GeneratedAddanewdeviceWidget16(),
              )
            ]),
      ),
    ));
  }
}
