import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_dishwaterWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedGradientBackgroundWallpaper00318Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_refrigeratorWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedJamqrcodeWidget1.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_stoveWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_coffeemakerWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_electricstoveWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedFrame33Widget11.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_microwaveWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_electricityWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedFrameWidget25.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_routerWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_waterWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_washingmachineWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedADDANEWDEVICEWidget1.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_socketsWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox9widget/generated/GeneratedIcon_televisionWidget.dart';

/* Frame iPhone 11 Pro / X - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedDataWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -183.0,
                  top: -394.0,
                  right: null,
                  bottom: null,
                  width: 886.0,
                  height: 1920.0,
                  child: GeneratedGradientBackgroundWallpaper00318Widget(),
                ),
                Positioned(
                  left: 70.0,
                  top: 70.0,
                  right: null,
                  bottom: null,
                  width: 214.0,
                  height: 33.0,
                  child: GeneratedADDANEWDEVICEWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 9.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 44.0,
                  child: GeneratedFrame33Widget11(),
                ),
                Positioned(
                  left: 34.0,
                  top: 70.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedFrameWidget25(),
                ),
                Positioned(
                  left: 321.0,
                  top: 67.0,
                  right: null,
                  bottom: null,
                  width: 39.0,
                  height: 34.0,
                  child: GeneratedJamqrcodeWidget1(),
                ),
                Positioned(
                  left: 25.0,
                  top: 164.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_refrigeratorWidget(),
                ),
                Positioned(
                  left: 174.0,
                  top: 163.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_coffeemakerWidget(),
                ),
                Positioned(
                  left: 98.0,
                  top: 249.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_waterWidget(),
                ),
                Positioned(
                  left: 98.0,
                  top: 164.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_electricityWidget(),
                ),
                Positioned(
                  left: 260.0,
                  top: 163.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_socketsWidget(),
                ),
                Positioned(
                  left: 172.0,
                  top: 251.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_dishwaterWidget(),
                ),
                Positioned(
                  left: 25.0,
                  top: 255.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_washingmachineWidget(),
                ),
                Positioned(
                  left: 260.0,
                  top: 249.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_stoveWidget(),
                ),
                Positioned(
                  left: 260.0,
                  top: 337.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_microwaveWidget(),
                ),
                Positioned(
                  left: 178.0,
                  top: 344.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_electricstoveWidget(),
                ),
                Positioned(
                  left: 101.0,
                  top: 335.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_televisionWidget(),
                ),
                Positioned(
                  left: 27.0,
                  top: 341.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: GeneratedIcon_routerWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
