import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatediphone11prox4widget/generated/GeneratedGradientBackgroundWallpaper00313Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox4widget/generated/GeneratedAddanewdeviceWidget12.dart';
import 'package:flutterapp/conservapp/generatediphone11prox4widget/generated/GeneratedFrame33Widget7.dart';
import 'package:flutterapp/conservapp/generatediphone11prox4widget/generated/GeneratedAddanewdeviceWidget13.dart';
import 'package:flutterapp/conservapp/generatediphone11prox4widget/generated/GeneratedSmartWidget1.dart';

/* Frame iPhone 11 Pro / X - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -180.0,
                top: -443.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper00313Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 91.0,
                child: GeneratedSmartWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedFrame33Widget7(),
              ),
              Positioned(
                left: 25.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedAddanewdeviceWidget12(),
              ),
              Positioned(
                left: 25.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedAddanewdeviceWidget13(),
              )
            ]),
      ),
    ));
  }
}
