import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatediphone11prox2widget/generated/GeneratedFrame33Widget5.dart';
import 'package:flutterapp/conservapp/generatediphone11prox2widget/generated/GeneratedHomemanagementWidget2.dart';
import 'package:flutterapp/conservapp/generatediphone11prox2widget/generated/GeneratedAddanewdeviceWidget10.dart';
import 'package:flutterapp/conservapp/generatediphone11prox2widget/generated/GeneratedGradientBackgroundWallpaper00311Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox2widget/generated/GeneratedAddanewdeviceWidget8.dart';
import 'package:flutterapp/conservapp/generatediphone11prox2widget/generated/GeneratedAddanewdeviceWidget9.dart';

/* Frame iPhone 11 Pro / X - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -443.0,
                top: -125.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper00311Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 88.0,
                child: GeneratedHomemanagementWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedAddanewdeviceWidget8(),
              ),
              Positioned(
                left: 20.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedAddanewdeviceWidget9(),
              ),
              Positioned(
                left: 20.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedAddanewdeviceWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 7.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedFrame33Widget5(),
              )
            ]),
      ),
    ));
  }
}
