import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatediphone11prox8widget/generated/Generated01Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox8widget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox8widget/generated/GeneratedPowerconsumptionsummaryWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox8widget/generated/GeneratedGradientBackgroundWallpaper00317Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox8widget/generated/Generated02Widget.dart';

/* Frame iPhone 11 Pro / X - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -232.0,
                top: -372.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper00317Widget(),
              ),
              Positioned(
                left: -1.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 378.0,
                height: 213.0,
                child: GeneratedPowerconsumptionsummaryWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 330.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 638.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 45.0,
                child: Generated01Widget(),
              ),
              Positioned(
                left: 193.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 60.0,
                child: Generated02Widget(),
              )
            ]),
      ),
    ));
  }
}
