import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatedscreen1widget/generated/GeneratedGradientBackgroundWallpaper0031Widget.dart';
import 'package:flutterapp/conservapp/generatedscreen1widget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/conservapp/generatedscreen1widget/generated/GeneratedSignupWidget.dart';
import 'package:flutterapp/conservapp/generatedscreen1widget/generated/GeneratedRectangle78Widget.dart';
import 'package:flutterapp/conservapp/generatedscreen1widget/generated/GeneratedConservMakeYourHomeSmartWidget.dart';

/* Frame screen 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -285.0,
                top: -585.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper0031Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 135.0,
                child: GeneratedConservMakeYourHomeSmartWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 571.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 658.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedSignupWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 246.0,
                child: GeneratedRectangle78Widget(),
              )
            ]),
      ),
    ));
  }
}
