import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatediphone11prox3widget/generated/GeneratedFrame33Widget6.dart';
import 'package:flutterapp/conservapp/generatediphone11prox3widget/generated/GeneratedGradientBackgroundWallpaper00312Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox3widget/generated/GeneratedHomeautomationsavesyourtimeandeffortbyautomatingroutine.dart';
import 'package:flutterapp/conservapp/generatediphone11prox3widget/generated/GeneratedAutomationWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox3widget/generated/GeneratedAddanewdeviceWidget11.dart';

/* Frame iPhone 11 Pro / X - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -239.0,
                top: -349.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper00312Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 7.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedFrame33Widget6(),
              ),
              Positioned(
                left: 22.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedAddanewdeviceWidget11(),
              ),
              Positioned(
                left: 13.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 91.0,
                child: GeneratedAutomationWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 99.0,
                child:
                    GeneratedHomeautomationsavesyourtimeandeffortbyautomatingroutine(),
              )
            ]),
      ),
    ));
  }
}
