import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatedmydeviceswidget/generated/GeneratedGradientBackgroundWallpaper0034Widget.dart';
import 'package:flutterapp/conservapp/generatedmydeviceswidget/generated/GeneratedFrame42Widget5.dart';
import 'package:flutterapp/conservapp/generatedmydeviceswidget/generated/GeneratedFrame41Widget.dart';
import 'package:flutterapp/conservapp/generatedmydeviceswidget/generated/GeneratedMyDevicesWidget1.dart';
import 'package:flutterapp/conservapp/generatedmydeviceswidget/generated/GeneratedFrame33Widget1.dart';
import 'package:flutterapp/conservapp/generatedmydeviceswidget/generated/GeneratedFrame38Widget.dart';
import 'package:flutterapp/conservapp/generatedmydeviceswidget/generated/GeneratedFrame39Widget.dart';
import 'package:flutterapp/conservapp/generatedmydeviceswidget/generated/GeneratedFrame40Widget.dart';
import 'package:flutterapp/conservapp/generatedmydeviceswidget/generated/GeneratedGgsmarthomecookerWidget.dart';
import 'package:flutterapp/conservapp/generatedmydeviceswidget/generated/GeneratedFrame37Widget.dart';
import 'package:flutterapp/conservapp/generatedmydeviceswidget/generated/GeneratedFrameWidget1.dart';

/* Frame My Devices
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMyDevicesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -264.0,
                top: -434.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper0034Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget1(),
              ),
              Positioned(
                left: 47.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 33.0,
                child: GeneratedMyDevicesWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 120.0,
                child: GeneratedFrame37Widget(),
              ),
              Positioned(
                left: 196.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 120.0,
                child: GeneratedFrame38Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 120.0,
                child: GeneratedFrame39Widget(),
              ),
              Positioned(
                left: 198.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 120.0,
                child: GeneratedFrame40Widget(),
              ),
              Positioned(
                left: 187.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 85.0,
                child: GeneratedGgsmarthomecookerWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 120.0,
                child: GeneratedFrame41Widget(),
              ),
              Positioned(
                left: 201.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 120.0,
                child: GeneratedFrame42Widget5(),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedFrame33Widget1(),
              )
            ]),
      ),
    ));
  }
}
