import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generateddatawidget/generated/GeneratedGradientBackgroundWallpaper0039Widget.dart';
import 'package:flutterapp/conservapp/generateddatawidget/generated/GeneratedFrame33Widget3.dart';
import 'package:flutterapp/conservapp/generateddatawidget/generated/GeneratedFETCHINGYOURDATAWidget.dart';

/* Frame Data
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDataWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedIPhone11ProX8Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -196.0,
                  top: -380.0,
                  right: null,
                  bottom: null,
                  width: 886.0,
                  height: 1920.0,
                  child: GeneratedGradientBackgroundWallpaper0039Widget(),
                ),
                Positioned(
                  left: 44.0,
                  top: 300.0,
                  right: null,
                  bottom: null,
                  width: 290.0,
                  height: 213.0,
                  child: GeneratedFETCHINGYOURDATAWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 44.0,
                  child: GeneratedFrame33Widget3(),
                )
              ]),
        ),
      ),
    ));
  }
}
