import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatedloginwidget2/generated/GeneratedFrame26Widget1.dart';
import 'package:flutterapp/conservapp/generatedloginwidget2/generated/GeneratedGradientBackgroundWallpaper0032Widget.dart';
import 'package:flutterapp/conservapp/generatedloginwidget2/generated/GeneratedWELCOMEWidget.dart';
import 'package:flutterapp/conservapp/generatedloginwidget2/generated/GeneratedLoginWidget3.dart';
import 'package:flutterapp/conservapp/generatedloginwidget2/generated/GeneratedGroup18Widget.dart';

/* Frame Login 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -280.0,
                top: -413.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper0032Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 60.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 60.0,
                child: GeneratedFrame26Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedLoginWidget3(),
              ),
              Positioned(
                left: 41.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 91.0,
                child: GeneratedWELCOMEWidget(),
              )
            ]),
      ),
    ));
  }
}
