import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedGroup19Widget2.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedAddanewdeviceWidget7.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedFrame43Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedFrame33Widget4.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedFrame47Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedFrame46Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedGroup18Widget2.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedFrame42Widget7.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedGradientBackgroundWallpaper00310Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedFrame45Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedFrame44Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox1widget/generated/GeneratedCreateahomeWidget.dart';

/* Frame iPhone 11 Pro / X - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -237.0,
                top: -335.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper00310Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 88.0,
                child: GeneratedCreateahomeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 60.0,
                child: GeneratedGroup18Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 60.0,
                child: GeneratedGroup19Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame42Widget7(),
              ),
              Positioned(
                left: 191.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame43Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame44Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame45Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame46Widget(),
              ),
              Positioned(
                left: 191.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame47Widget(),
              ),
              Positioned(
                left: 92.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 44.0,
                child: GeneratedAddanewdeviceWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedFrame33Widget4(),
              )
            ]),
      ),
    ));
  }
}
