import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatediphone11prox5widget/generated/GeneratedCreateataskandtapittorunThisenableseasycontrolofyoursma.dart';
import 'package:flutterapp/conservapp/generatediphone11prox5widget/generated/GeneratedTAPTORUNWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox5widget/generated/GeneratedAddanewdeviceWidget14.dart';
import 'package:flutterapp/conservapp/generatediphone11prox5widget/generated/GeneratedGradientBackgroundWallpaper00314Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox5widget/generated/GeneratedFrame33Widget8.dart';

/* Frame iPhone 11 Pro / X - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -177.0,
                top: -361.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper00314Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedFrame33Widget8(),
              ),
              Positioned(
                left: 4.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 91.0,
                child: GeneratedTAPTORUNWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 99.0,
                child:
                    GeneratedCreateataskandtapittorunThisenableseasycontrolofyoursma(),
              ),
              Positioned(
                left: 20.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedAddanewdeviceWidget14(),
              )
            ]),
      ),
    ));
  }
}
