import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatedaddanewdevice1widget/generated/GeneratedGradientBackgroundWallpaper0036Widget.dart';
import 'package:flutterapp/conservapp/generatedaddanewdevice1widget/generated/GeneratedFrameWidget9.dart';
import 'package:flutterapp/conservapp/generatedaddanewdevice1widget/generated/GeneratedAddanewdeviceWidget5.dart';
import 'package:flutterapp/conservapp/generatedaddanewdevice1widget/generated/GeneratedJamqrcodeWidget.dart';
import 'package:flutterapp/conservapp/generatedaddanewdevice1widget/generated/GeneratedFrame33Widget2.dart';
import 'package:flutterapp/conservapp/generatedaddanewdevice1widget/generated/GeneratedADDANEWDEVICEWidget.dart';
import 'package:flutterapp/conservapp/generatedaddanewdevice1widget/generated/GeneratedAddanewdeviceWidget4.dart';

/* Frame add a new device 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddanewdevice1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -245.0,
                top: -692.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper0036Widget(),
              ),
              Positioned(
                left: 316.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 34.0,
                child: GeneratedJamqrcodeWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 33.0,
                child: GeneratedADDANEWDEVICEWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFrameWidget9(),
              ),
              Positioned(
                left: 17.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedAddanewdeviceWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedAddanewdeviceWidget5(),
              ),
              Positioned(
                left: -3.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedFrame33Widget2(),
              )
            ]),
      ),
    ));
  }
}
