import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatediphone11prox6widget/generated/GeneratedFrame42Widget14.dart';
import 'package:flutterapp/conservapp/generatediphone11prox6widget/generated/GeneratedFrame33Widget9.dart';
import 'package:flutterapp/conservapp/generatediphone11prox6widget/generated/GeneratedFrame46Widget1.dart';
import 'package:flutterapp/conservapp/generatediphone11prox6widget/generated/GeneratedMyhomeWidget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox6widget/generated/GeneratedAddanewdeviceWidget15.dart';
import 'package:flutterapp/conservapp/generatediphone11prox6widget/generated/GeneratedGradientBackgroundWallpaper00315Widget.dart';
import 'package:flutterapp/conservapp/generatediphone11prox6widget/generated/GeneratedFrame45Widget1.dart';
import 'package:flutterapp/conservapp/generatediphone11prox6widget/generated/GeneratedFrame44Widget1.dart';
import 'package:flutterapp/conservapp/generatediphone11prox6widget/generated/GeneratedFrame47Widget1.dart';
import 'package:flutterapp/conservapp/generatediphone11prox6widget/generated/GeneratedFrame43Widget4.dart';

/* Frame iPhone 11 Pro / X - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -341.0,
                top: -664.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper00315Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 88.0,
                child: GeneratedMyhomeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedFrame33Widget9(),
              ),
              Positioned(
                left: 30.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame42Widget14(),
              ),
              Positioned(
                left: 207.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame45Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame46Widget1(),
              ),
              Positioned(
                left: 207.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame43Widget4(),
              ),
              Positioned(
                left: 30.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame44Widget1(),
              ),
              Positioned(
                left: 204.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 76.0,
                child: GeneratedFrame47Widget1(),
              ),
              Positioned(
                left: 102.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 44.0,
                child: GeneratedAddanewdeviceWidget15(),
              )
            ]),
      ),
    ));
  }
}
