import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatedhomewidget/generated/GeneratedGradientBackgroundWallpaper0033Widget.dart';
import 'package:flutterapp/conservapp/generatedhomewidget/generated/GeneratedHiSamWelcometoSamshomeWidget.dart';
import 'package:flutterapp/conservapp/generatedhomewidget/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/conservapp/generatedhomewidget/generated/GeneratedEllipse36Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/conservapp/generatedhomewidget/generated/GeneratedAddanewdeviceWidget3.dart';
import 'package:flutterapp/conservapp/generatedhomewidget/generated/GeneratedMydevicesWidget.dart';
import 'package:flutterapp/conservapp/generatedhomewidget/generated/GeneratedFrame33Widget.dart';
import 'package:flutterapp/conservapp/generatedhomewidget/generated/GeneratedAddanewdeviceWidget.dart';
import 'package:flutterapp/conservapp/generatedhomewidget/generated/GeneratedAddanewdeviceWidget2.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: -1.00,
            b: 0.00,
            c: 0.00,
            d: 1.00,
            child: ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                width: 375.0,
                height: 812.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Container(
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      Positioned(
                        left: -184.0,
                        top: -356.0,
                        right: null,
                        bottom: null,
                        width: 886.0,
                        height: 1920.0,
                        child: GeneratedGradientBackgroundWallpaper0033Widget(),
                      ),
                      Positioned(
                        left: 315.0,
                        top: 83.0,
                        right: null,
                        bottom: null,
                        width: 267.0,
                        height: 97.0,
                        child: GeneratedHiSamWelcometoSamshomeWidget(),
                      ),
                      Positioned(
                        left: 321.0,
                        top: 202.0,
                        right: null,
                        bottom: null,
                        width: 277.0,
                        height: 86.0,
                        child: GeneratedGroup25Widget(),
                      ),
                      Positioned(
                        left: 355.0,
                        top: 382.0,
                        right: null,
                        bottom: null,
                        width: 335.0,
                        height: 48.0,
                        child: GeneratedAddanewdeviceWidget(),
                      ),
                      Positioned(
                        left: 350.0,
                        top: 475.0,
                        right: null,
                        bottom: null,
                        width: 335.0,
                        height: 48.0,
                        child: GeneratedMydevicesWidget(),
                      ),
                      Positioned(
                        left: 98.0,
                        top: 83.0,
                        right: null,
                        bottom: null,
                        width: 49.0,
                        height: 51.0,
                        child: GeneratedEllipse36Widget(),
                      ),
                      Positioned(
                        left: 352.0,
                        top: 568.0,
                        right: null,
                        bottom: null,
                        width: 335.0,
                        height: 48.0,
                        child: GeneratedAddanewdeviceWidget2(),
                      ),
                      Positioned(
                        left: 382.0,
                        top: 15.0,
                        right: null,
                        bottom: null,
                        width: 375.0,
                        height: 44.0,
                        child: GeneratedFrame33Widget(),
                      ),
                      Positioned(
                        left: 350.0,
                        top: 661.0,
                        right: null,
                        bottom: null,
                        width: 335.0,
                        height: 48.0,
                        child: GeneratedAddanewdeviceWidget3(),
                      )
                    ]),
              ),
            )));
  }
}
