import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatedsignupwidget1/generated/GeneratedGradientBackgroundWallpaper0037Widget.dart';
import 'package:flutterapp/conservapp/generatedsignupwidget1/generated/GeneratedSIgnUPWidget.dart';
import 'package:flutterapp/conservapp/generatedsignupwidget1/generated/GeneratedFrame26Widget2.dart';
import 'package:flutterapp/conservapp/generatedsignupwidget1/generated/GeneratedGroup18Widget1.dart';
import 'package:flutterapp/conservapp/generatedsignupwidget1/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/conservapp/generatedsignupwidget1/generated/GeneratedSignupWidget1.dart';

/* Frame Sign Up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -205.0,
                top: -310.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper0037Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 60.0,
                child: GeneratedFrame26Widget2(),
              ),
              Positioned(
                left: 14.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 60.0,
                child: GeneratedGroup18Widget1(),
              ),
              Positioned(
                left: 14.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 60.0,
                child: GeneratedGroup19Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 88.0,
                child: GeneratedSIgnUPWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedSignupWidget1(),
              )
            ]),
      ),
    ));
  }
}
