import 'package:flutter/material.dart';
import 'package:flutterapp/conservapp/generatedchargewidget/generated/GeneratedGradientBackgroundWallpaper0038Widget.dart';
import 'package:flutterapp/conservapp/generatedchargewidget/generated/GeneratedGroup19Widget1.dart';
import 'package:flutterapp/conservapp/generatedchargewidget/generated/GeneratedAddanewdeviceWidget6.dart';
import 'package:flutterapp/conservapp/generatedchargewidget/generated/GeneratedEnteryourelectricitychargesWidget.dart';

/* Frame Charge
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChargeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -199.0,
                top: -434.0,
                right: null,
                bottom: null,
                width: 886.0,
                height: 1920.0,
                child: GeneratedGradientBackgroundWallpaper0038Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 89.0,
                child: GeneratedEnteryourelectricitychargesWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 57.0,
                child: GeneratedGroup19Widget1(),
              ),
              Positioned(
                left: 102.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 44.0,
                child: GeneratedAddanewdeviceWidget6(),
              )
            ]),
      ),
    ));
  }
}
